package com.panuwatjan.blognonestory;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.panuwatjan.blognonestory.BlognoneTags;
import com.panuwatjan.blognonestory.BlognoneTopicCache;
import com.panuwatjan.blognonestory.BlognoneFavoriteTopic;
import com.panuwatjan.blognonestory.BlognoneHistoryTopic;
import com.panuwatjan.blognonestory.BlognoneJobsCache;
import com.panuwatjan.blognonestory.BlognoneFavoriteJobs;

import com.panuwatjan.blognonestory.BlognoneTagsDao;
import com.panuwatjan.blognonestory.BlognoneTopicCacheDao;
import com.panuwatjan.blognonestory.BlognoneFavoriteTopicDao;
import com.panuwatjan.blognonestory.BlognoneHistoryTopicDao;
import com.panuwatjan.blognonestory.BlognoneJobsCacheDao;
import com.panuwatjan.blognonestory.BlognoneFavoriteJobsDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig blognoneTagsDaoConfig;
    private final DaoConfig blognoneTopicCacheDaoConfig;
    private final DaoConfig blognoneFavoriteTopicDaoConfig;
    private final DaoConfig blognoneHistoryTopicDaoConfig;
    private final DaoConfig blognoneJobsCacheDaoConfig;
    private final DaoConfig blognoneFavoriteJobsDaoConfig;

    private final BlognoneTagsDao blognoneTagsDao;
    private final BlognoneTopicCacheDao blognoneTopicCacheDao;
    private final BlognoneFavoriteTopicDao blognoneFavoriteTopicDao;
    private final BlognoneHistoryTopicDao blognoneHistoryTopicDao;
    private final BlognoneJobsCacheDao blognoneJobsCacheDao;
    private final BlognoneFavoriteJobsDao blognoneFavoriteJobsDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        blognoneTagsDaoConfig = daoConfigMap.get(BlognoneTagsDao.class).clone();
        blognoneTagsDaoConfig.initIdentityScope(type);

        blognoneTopicCacheDaoConfig = daoConfigMap.get(BlognoneTopicCacheDao.class).clone();
        blognoneTopicCacheDaoConfig.initIdentityScope(type);

        blognoneFavoriteTopicDaoConfig = daoConfigMap.get(BlognoneFavoriteTopicDao.class).clone();
        blognoneFavoriteTopicDaoConfig.initIdentityScope(type);

        blognoneHistoryTopicDaoConfig = daoConfigMap.get(BlognoneHistoryTopicDao.class).clone();
        blognoneHistoryTopicDaoConfig.initIdentityScope(type);

        blognoneJobsCacheDaoConfig = daoConfigMap.get(BlognoneJobsCacheDao.class).clone();
        blognoneJobsCacheDaoConfig.initIdentityScope(type);

        blognoneFavoriteJobsDaoConfig = daoConfigMap.get(BlognoneFavoriteJobsDao.class).clone();
        blognoneFavoriteJobsDaoConfig.initIdentityScope(type);

        blognoneTagsDao = new BlognoneTagsDao(blognoneTagsDaoConfig, this);
        blognoneTopicCacheDao = new BlognoneTopicCacheDao(blognoneTopicCacheDaoConfig, this);
        blognoneFavoriteTopicDao = new BlognoneFavoriteTopicDao(blognoneFavoriteTopicDaoConfig, this);
        blognoneHistoryTopicDao = new BlognoneHistoryTopicDao(blognoneHistoryTopicDaoConfig, this);
        blognoneJobsCacheDao = new BlognoneJobsCacheDao(blognoneJobsCacheDaoConfig, this);
        blognoneFavoriteJobsDao = new BlognoneFavoriteJobsDao(blognoneFavoriteJobsDaoConfig, this);

        registerDao(BlognoneTags.class, blognoneTagsDao);
        registerDao(BlognoneTopicCache.class, blognoneTopicCacheDao);
        registerDao(BlognoneFavoriteTopic.class, blognoneFavoriteTopicDao);
        registerDao(BlognoneHistoryTopic.class, blognoneHistoryTopicDao);
        registerDao(BlognoneJobsCache.class, blognoneJobsCacheDao);
        registerDao(BlognoneFavoriteJobs.class, blognoneFavoriteJobsDao);
    }
    
    public void clear() {
        blognoneTagsDaoConfig.getIdentityScope().clear();
        blognoneTopicCacheDaoConfig.getIdentityScope().clear();
        blognoneFavoriteTopicDaoConfig.getIdentityScope().clear();
        blognoneHistoryTopicDaoConfig.getIdentityScope().clear();
        blognoneJobsCacheDaoConfig.getIdentityScope().clear();
        blognoneFavoriteJobsDaoConfig.getIdentityScope().clear();
    }

    public BlognoneTagsDao getBlognoneTagsDao() {
        return blognoneTagsDao;
    }

    public BlognoneTopicCacheDao getBlognoneTopicCacheDao() {
        return blognoneTopicCacheDao;
    }

    public BlognoneFavoriteTopicDao getBlognoneFavoriteTopicDao() {
        return blognoneFavoriteTopicDao;
    }

    public BlognoneHistoryTopicDao getBlognoneHistoryTopicDao() {
        return blognoneHistoryTopicDao;
    }

    public BlognoneJobsCacheDao getBlognoneJobsCacheDao() {
        return blognoneJobsCacheDao;
    }

    public BlognoneFavoriteJobsDao getBlognoneFavoriteJobsDao() {
        return blognoneFavoriteJobsDao;
    }

}
