package com.benznestdeveloper.blognonestory;

/**
 * Created by benznest on 16-Mar-18.
 */

public class MyThemeName {
    public static String[] themeName ={"Bangkok",
            "Pattaya",
            "Krabi",
            "Kanchanaburi",
            "Kalasin",
            "Kamphaengphet",
            "Khonkaen",
            "Chiang Rai",
            "Chiang Mai",
            "Chanthaburi",
            "Chachoengsao",
            "Chonburi",
            "Chainat",
            "Chaiyaphum",
            "Chumphon",
            "Trang",
            "Trat",
            "Tak",
            "Nk.Nayok",
            "Nk.Pathom",
            "Nk.Phanom",
            "Nk.Ratchasima",
            "Nk.Si",
            "Nk.Sawan",
            "Nonthaburi",
            "Narathiwat",
            "Nan",
            "Bueng Kan",
            "Buri Ram",
            "Pathumthani",
            "Pc.khirikhan",
            "Prachinburi",
            "Pattani",
            "Phranakhon",
            "Phayao",
            "Phangnga",
            "Phatthalung ",
            "Phichit",
            "Phitsanulok",
            "Phuket",
            "Mahasarakham",
            "Mukdahan",
            "Yala",
            "Yasothon",
            "Ranong",
            "Rayong",
            "Ratchaburi",
            "Roi-et",
            "Lopburi",
            "Lampang",
            "Lamphun",
            "Sisaket",
            "Sakonnakhon",
            "Songkhla",
            "Satun",
            "Sm.Prakan",
            "Sm.Songkhram",
            "Sm.Sakhon",
            "Saraburi",
            "Sa-kaeo",
            "Singburi",
            "Suphanburi",
            "Suratthani",
            "Surin",
            "Sukhothai",
            "Nongkhai",
            "Nongbualamphu",
            "Amnatcharoen",
            "Udonthani",
            "Uttaradit",
            "Uthaithani",
            "Ubonratchathani",
            "Ang Thong",
            "Phetchaburi",
            "Phetchabun",
            "Loei",
            "Phrae",
            "Maehongson"
    };
}
